const menu=document.querySelector('.menu-button');
const nav=document.querySelector('#navigation');
menu.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));nav.classList.toggle('open',!expanded)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}});
document.querySelectorAll('[data-kind]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#kind').value=a.dataset.kind}));
document.querySelector('#request-form').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#name');if(!name.value.trim()){name.setCustomValidity('Пожалуйста, укажите ваше имя.');name.reportValidity();return}const text=['Здравствуйте! Меня зовут '+name.value.trim()+'.','Интересует: '+document.querySelector('#kind').value+'.',document.querySelector('#idea').value.trim(),'Хочу обсудить проект и замер.'].filter(Boolean).join('\n');window.open('https://wa.me/77011628888?text='+encodeURIComponent(text),'_blank','noopener,noreferrer')});
document.querySelector('#name').addEventListener('input',e=>e.target.setCustomValidity(''));
const lightbox=document.querySelector('#lightbox');
document.querySelectorAll('.project').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#lightbox-image').src=button.dataset.image;document.querySelector('#lightbox-image').alt=button.dataset.title;document.querySelector('#lightbox-title').textContent=button.dataset.title;lightbox.showModal()}));
lightbox.querySelector('.close').addEventListener('click',()=>lightbox.close());
lightbox.addEventListener('click',e=>{const r=lightbox.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)lightbox.close()});
document.querySelector('#year').textContent=new Date().getFullYear();
